spring.application.name=stockcontrol

# Conexao com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/stockcontrol_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Configuracao JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truespring.application.name=stockcontrol

# Porta da aplicacao
server.port=8081

